
CREATE TABLE SEC_USER
(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1)
  , USERNAME VARCHAR(64) NOT NULL
  , PASSWORD VARCHAR(64) NOT NULL
  , EMAIL VARCHAR(64) NOT NULL
  , NAME VARCHAR(64)
  , SURNAME VARCHAR(64)
  , GENDER VARCHAR(6)
  , PHOTO BLOB
  , COUNTRY VARCHAR(64)
  , CITY VARCHAR(64)
  , BIO CLOB
  , ENABLED CHAR(1) DEFAULT '1' NOT NULL
  , CONSTRAINT SEC_USER_PK PRIMARY KEY (ID)
  , CONSTRAINT SEC_USER_UNIQUE_USERNAME UNIQUE (USERNAME)
  , CONSTRAINT SEC_USER_UNIQUE_EMAIL UNIQUE (EMAIL)
  , CONSTRAINT CHECK_GENDER CHECK (GENDER in ('MALE', 'FEMALE'))
  , CONSTRAINT CHECK_ENABLED CHECK (enabled IN  ('0','1'))

);


CREATE TABLE EVENT
(
    ID INTEGER NOT NULL
  , NAME VARCHAR(64) NOT NULL
  , SEC_USER_ID INTEGER NOT NULL
  , DESCRIPTION CLOB
  , COUNTRY VARCHAR(64)
  , CITY VARCHAR(64)
  , ADDRESS VARCHAR(64)
  , GPS_LATITUDE DOUBLE
  , GPS_LONGITUDE DOUBLE
  , EVENT_TIME TIMESTAMP
  , CONSTRAINT EVENT_PK PRIMARY KEY (ID)
  , CONSTRAINT EVENT_SEC_USER_FK FOREIGN KEY (SEC_USER_ID) REFERENCES SEC_USER (ID)
);

CREATE TABLE COMMENTARY
(
    ID INTEGER NOT NULL
  , EVENT_ID INTEGER NOT NULL
  , SEC_USER_ID INTEGER NOT NULL
  , COMMENT_TIME TIMESTAMP
  , MESSAGE CLOB
  , CONSTRAINT COMMENTARY_PK PRIMARY KEY (ID)
  , CONSTRAINT COMMENTARY_EVENT_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENT (ID)
  , CONSTRAINT COMMENTARY_SEC_USER_FK FOREIGN KEY (SEC_USER_ID) REFERENCES SEC_USER (ID)
);

CREATE TABLE VIDEO
(
    ID INTEGER NOT NULL
  , EVENT_ID INTEGER NOT NULL
  , VIDEO_DATA BLOB NOT NULL
  , CONSTRAINT VIDEO_PK PRIMARY KEY (ID)
  , CONSTRAINT VIDEO_EVENT_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENT (ID)
);


CREATE TABLE PHOTO
(
    ID INTEGER NOT NULL
  , EVENT_ID INTEGER NOT NULL
  , PHOTO_DATA BLOB NOT NULL
  , CONSTRAINT PHOTO_PK PRIMARY KEY (ID)
  , CONSTRAINT PHOTO_EVENT_FK
FOREIGN KEY (EVENT_ID)
REFERENCES EVENT (ID)
);


CREATE TABLE TAG
(
    ID INTEGER NOT NULL
  , EVENT_ID INTEGER NOT NULL
  , TAG_NAME VARCHAR(64) NOT NULL
  , CONSTRAINT TAG_PK PRIMARY KEY (ID)
  , CONSTRAINT TAG_EVENT_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENT (ID)
);

CREATE TABLE authority(
  id INTEGER NOT NULL ,
  authority VARCHAR(64) NOT NULL ,
  CONSTRAINT authority_pk PRIMARY KEY (id),
  CONSTRAINT authority_authority_unique UNIQUE (authority)
);

CREATE TABLE sec_user_authority(
  sec_user_id INTEGER NOT NULL ,
  authority_id INTEGER NOT NULL,
  CONSTRAINT sec_user_authority_pk PRIMARY KEY (sec_user_id,authority_id),
  CONSTRAINT sec_user_authority_sec_user_fk FOREIGN KEY (sec_user_id) REFERENCES sec_user (id),
  CONSTRAINT sec_user_authority_fk FOREIGN KEY (authority_id) REFERENCES authority (id)

);
