
ALTER TABLE VIDEO DROP COLUMN VIDEO_LINK;
ALTER TABLE VIDEO ADD ("VIDEO_DATA" BLOB NOT NULL);
ALTER TABLE PHOTO DROP COLUMN PHOTO_LINK;
ALTER TABLE PHOTO ADD ("PHOTO_DATA" BLOB NOT NULL);
ALTER TABLE TAG ADD TAG_NAME VARCHAR2(64 char) NOT NULL;
ALTER TABLE EVENT DROP COLUMN DESCRIPTION;
ALTER TABLE EVENT ADD ("DESCRIPTION" CLOB);