
ALTER TABLE VIDEO DROP COLUMN VIDEO_LINK;
ALTER TABLE VIDEO ADD ("VIDEO_DATA" BLOB);
ALTER TABLE PHOTO DROP COLUMN PHOTO_LINK;
ALTER TABLE PHOTO ADD ("PHOTO_DATA" BLOB);
ALTER TABLE TAG ADD TAG_NAME VARCHAR2(64 char) NOT NULL;