CREATE SEQUENCE AUTHORITY_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COMMENTARY_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EVENT_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PHOTO_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEC_USER_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TAG_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE VIDEO_ID_SEQ START WITH 1 INCREMENT BY 1;